# Generated by Django 2.2.13 on 2020-07-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20190327_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productclass',
            name='popular',
            field=models.BooleanField(default=True),
        ),
    ]
