# Generated by Django 2.2.13 on 2020-07-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20200723_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productclass',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='productclass',
            name='popular',
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.BooleanField(default=True),
        ),
    ]
