# Generated by Django 2.2.13 on 2020-08-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_auto_20200820_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_ar',
            new_name='name_Filipino',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_en',
            new_name='name_arabic',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_fi',
            new_name='name_english',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_ar',
            new_name='description_Filipino',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_en',
            new_name='description_arabic',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_fi',
            new_name='description_english',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_ar',
            new_name='title_Filipino',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_en',
            new_name='title_arabic',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_fi',
            new_name='title_english',
        ),
    ]
