# Generated by Django 2.2.13 on 2020-08-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_auto_20200825_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_english',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_english',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_english',
            new_name='title_en',
        ),
    ]
