# Generated by Django 2.2.13 on 2020-08-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_auto_20200825_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_Filipino',
            new_name='name_Fp',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_arabic',
            new_name='name_ab',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_english',
            new_name='name_sh',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_Filipino',
            new_name='description_Fp',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_arabic',
            new_name='description_ab',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_english',
            new_name='description_sh',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_Filipino',
            new_name='title_Fp',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_arabic',
            new_name='title_ab',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_english',
            new_name='title_sh',
        ),
    ]
