# Generated by Django 2.2.13 on 2020-08-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_auto_20200825_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_Fp',
            new_name='name_FI',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_ab',
            new_name='name_ar',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_sh',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_Fp',
            new_name='description_FI',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_ab',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_sh',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_Fp',
            new_name='title_FI',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_ab',
            new_name='title_ar',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_sh',
            new_name='title_en',
        ),
    ]
