# Generated by Django 2.2.13 on 2020-08-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20200825_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_FI',
            new_name='name_pi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_FI',
            new_name='description_pi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_FI',
            new_name='title_pi',
        ),
    ]
