# Generated by Django 2.2.13 on 2020-08-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_auto_20200825_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_pi',
            new_name='name_Pi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_pi',
            new_name='description_Pi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_pi',
            new_name='title_Pi',
        ),
    ]
