# Generated by Django 2.2.13 on 2020-08-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_auto_20200825_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_Pi',
            new_name='name_fi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_Pi',
            new_name='description_fi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_Pi',
            new_name='title_fi',
        ),
    ]
