# Generated by Django 2.2.13 on 2020-09-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_auto_20200825_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_fi',
            new_name='name_ph',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_fi',
            new_name='description_ph',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_fi',
            new_name='title_ph',
        ),
    ]
