# Generated by Django 2.2.13 on 2020-09-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_auto_20200903_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_pi',
            new_name='name_fil',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_pi',
            new_name='description_fil',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_pi',
            new_name='title_fil',
        ),
    ]
