# Generated by Django 2.2.13 on 2020-09-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_auto_20200903_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_fil',
            new_name='name_fi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_fil',
            new_name='description_fi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_fil',
            new_name='title_fi',
        ),
    ]
