# Generated by Django 2.2.13 on 2020-09-21 09:59

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_auto_20200903_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('أبيض', 'أبيض'), ('فضي', 'فضي'), ('روز جولد', 'روز جولد'), ('أسود', 'أسود'), ('بني', 'بني'), ('أزرق', 'أزرق')], default=False, max_length=31),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_seller',
            field=models.BooleanField(default=False),
        ),
    ]
