# Generated by Django 2.2.13 on 2020-09-21 10:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_auto_20200921_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('أبيض', 'أبيض'), ('فضي', 'فضي'), ('روز جولد', 'روز جولد'), ('أسود', 'أسود'), ('بني', 'بني'), ('أزرق', 'أزرق')], max_length=31),
        ),
    ]
