# Generated by Django 2.2.13 on 2020-09-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0042_auto_20200921_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_list',
        ),
        migrations.AddField(
            model_name='product',
            name='color_list',
            field=models.ManyToManyField(related_name='_product_color_list_+', to='catalogue.Product'),
        ),
    ]
