# Generated by Django 2.2.13 on 2020-09-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0044_auto_20200921_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_list',
        ),
        migrations.CreateModel(
            name='NameColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_color', models.ManyToManyField(to='catalogue.Product')),
            ],
        ),
    ]
