# Generated by Django 2.2.13 on 2020-09-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0045_auto_20200921_1256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NameColors',
            new_name='NameColor',
        ),
    ]
