# Generated by Django 2.2.13 on 2020-09-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0046_auto_20200921_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namecolor',
            name='name_color',
        ),
        migrations.AddField(
            model_name='namecolor',
            name='name_color',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
