# Generated by Django 2.2.13 on 2020-09-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0047_auto_20200921_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='namecolor',
            name='color',
            field=models.ManyToManyField(to='catalogue.Product'),
        ),
    ]
