# Generated by Django 2.2.13 on 2020-09-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0049_auto_20200921_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namecolor',
            name='name_color',
        ),
    ]
