# Generated by Django 2.2.13 on 2020-09-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0050_remove_namecolor_name_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namecolor',
            old_name='colour',
            new_name='color_list',
        ),
    ]
