# Generated by Django 2.2.13 on 2020-09-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0052_delete_namecolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_list', models.ManyToManyField(to='catalogue.Colour')),
            ],
        ),
    ]
