# Generated by Django 2.2.13 on 2020-09-21 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0053_namecolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='namecolor',
            name='name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='name', to='catalogue.Colour'),
            preserve_default=False,
        ),
    ]
